export const currentEndorTarget = 'endor-renderer-106cd82';

export const currentEndorVisualMedia = new Set([
  'cel_shaded',
  'paper_cutout',
  'pixel_broadcast',
  'archive_film',
  'neon_wireframe',
  'public_access_vhs',
  'signal_corruption',
  'stop_motion',
  'collage_zine',
  'ink_monochrome',
  'miniature_diorama',
  'corporate_vector',
  'claymation',
  'shadow_theatre',
  'hand_drawn',
  'thermal_camera',
  'ascii_terminal',
  'blueprint_schematic',
  'stained_glass',
  'xerox_punk',
  'storybook_wash',
  'isometric_manual',
]);
