import type { GeneratedSegmentDraft } from '@elsewhere-cable/schemas';

type DraftInput = Omit<GeneratedSegmentDraft, 'dialogue'> & {
  dialogue: Array<
    readonly [
      speaker: string,
      text: string,
      action: GeneratedSegmentDraft['dialogue'][number]['action'],
    ]
  >;
};

function draft(input: DraftInput): GeneratedSegmentDraft {
  return {
    ...input,
    dialogue: input.dialogue.map(([speaker, text, action]) => ({ speaker, text, action })),
  };
}

export const expandedDemoDrafts: GeneratedSegmentDraft[] = [
  draft({
    channelNumber: 4_700_219,
    channelName: 'Minutes From Tomorrow',
    programmeTitle: 'Apologies From the 4:15 Meeting',
    format: 'public_access',
    realityId: 'TOMORROW-MINUS-6',
    visualStyle: 'office_minutes_after_the_fact',
    visualMedium: 'public_access_vhs',
    castArchetype: 'paper_puppets',
    premise: 'Meeting minutes apologise for decisions the committee has not made yet.',
    tone: ['administrative', 'premature', 'dry'],
    dialogue: [
      ['Minute Seven', 'I regret recording your unanimous resignation next Thursday.', 'IDLE'],
      ['Chair Objector', 'I was planning to abstain from resigning.', 'REACTION_CONFUSED'],
      ['Minute Seven', 'Your abstention has already been described as moving.', 'POINT_AT'],
      ['Chair Objector', 'Please change moving to legally stationary.', 'FREEZE'],
    ],
    continuityFact: 'Official minutes can arrive before the meeting and feel remorse.',
    endingBeat: 'The blank agenda signs itself and leaves.',
  }),
  draft({
    channelNumber: 88_000_088,
    channelName: 'The Appliance Witness Network',
    programmeTitle: 'The Refrigerator Remembers Blue Curtains',
    format: 'news',
    realityId: 'KITCHEN-TRIBUNAL-12',
    visualStyle: 'domestic_testimony_network',
    visualMedium: 'cel_shaded',
    castArchetype: 'talking_objects',
    premise: 'A refrigerator gives live evidence about a family it preferred.',
    tone: ['forensic', 'jealous', 'domestic'],
    dialogue: [
      [
        'Anchor Tongs',
        'The witness has requested that the current kitchen look away.',
        'REACTION_NEUTRAL',
      ],
      [
        'Fridge Nine',
        'The blue-curtain family labelled leftovers with dates and intentions.',
        'PAUSE',
      ],
      ['Anchor Tongs', 'Did they ever describe you as merely an appliance?', 'LOOK_AT'],
      ['Fridge Nine', 'Only during the custody hearing for the ice tray.', 'FREEZE'],
    ],
    continuityFact: 'Fridge Nine retains favourable memories of the blue-curtain family.',
    endingBeat: 'The studio light goes out when the refrigerator door closes.',
  }),
  draft({
    channelNumber: 9_999_999_937,
    channelName: 'The Last Channel Before Numbers',
    programmeTitle: 'Counting Has Been Discontinued',
    format: 'ident',
    realityId: 'INTEGER-EDGE',
    visualStyle: 'terminal_numerical_boundary',
    visualMedium: 'signal_corruption',
    castArchetype: 'geometric_aliens',
    premise: 'A station beyond the usable number range asks arithmetic to turn back.',
    tone: ['formal', 'cosmic', 'final'],
    dialogue: [
      ['Boundary Clerk', 'You have reached the final channel that agrees to be counted.', 'IDLE'],
      ['Loose Decimal', 'May I stand quietly after the last digit?', 'REACTION_CONFUSED'],
      ['Boundary Clerk', 'There is no after. Please wait inside the nine.', 'POINT_AT'],
      ['Loose Decimal', 'It is already crowded with fractions.', 'FREEZE'],
    ],
    continuityFact: 'Channel numbering ends locally at a disputed cluster of nines.',
    endingBeat: 'One digit unhooks itself and falls upward.',
  }),
  draft({
    channelNumber: 7_777_014,
    channelName: 'Weather Inside Furniture',
    programmeTitle: 'Severe Conditions Behind the Wardrobe',
    format: 'news',
    realityId: 'INTERIOR-CLIMATE-4',
    visualStyle: 'soft_furnishing_forecast',
    visualMedium: 'paper_cutout',
    castArchetype: 'talking_objects',
    premise: 'A forecaster warns of indoor weather forming in unused furniture.',
    tone: ['reassuring', 'specific', 'damp'],
    dialogue: [
      [
        'Felt Meteorologist',
        'A linen front is pressing south through the spare-room wardrobe.',
        'POINT_AT',
      ],
      [
        'Drawer Correspondent',
        'I can confirm isolated socks are gathering into a system.',
        'REACTION_NEUTRAL',
      ],
      ['Felt Meteorologist', 'Residents should avoid opening anything inherited.', 'LOOK_AT'],
      ['Drawer Correspondent', 'Too late. The grandfather clock has developed tides.', 'FREEZE'],
    ],
    continuityFact: 'Inherited furniture can contain self-sustaining weather.',
    endingBeat: 'Rain begins falling horizontally between two shelves.',
  }),
  draft({
    channelNumber: 3_141_592_653,
    channelName: 'Circular Time Allocation',
    programmeTitle: 'Your Remaining Three Point One Minutes',
    format: 'public_access',
    realityId: 'PI-DISTRICT',
    visualStyle: 'civic_mathematics_counter',
    visualMedium: 'pixel_broadcast',
    castArchetype: 'geometric_aliens',
    premise: 'Citizens appeal when their day is rounded down by the time authority.',
    tone: ['precise', 'civic', 'anxious'],
    dialogue: [
      ['Clerk Radius', 'You were issued a circular lunch break with no agreed ending.', 'IDLE'],
      ['Citizen Arc', 'I returned when the sandwich met itself.', 'REACTION_CONFUSED'],
      ['Clerk Radius', 'That proves completion, not punctuality.', 'POINT_AT'],
      ['Citizen Arc', 'Then I request a corner where time cannot follow me.', 'FREEZE'],
    ],
    continuityFact: 'Circular breaks conclude when their contents meet themselves.',
    endingBeat: 'The queue bends into a ring around the clerk.',
  }),
  draft({
    channelNumber: 61_004_781,
    channelName: 'Animal Appeals Court',
    programmeTitle: 'Cat Versus the Indoor Voice',
    format: 'public_access',
    realityId: 'PET-LAW-31',
    visualStyle: 'daytime_courtroom_animals',
    visualMedium: 'stop_motion',
    castArchetype: 'talking_objects',
    premise: 'A cat prosecutes the concept of an indoor voice for suppressing midnight evidence.',
    tone: ['legalistic', 'indignant', 'furry'],
    dialogue: [
      ['Justice Pigeon', 'Counsel may knock one object from the bench before opening.', 'IDLE'],
      [
        'Mallow the Cat',
        'The indoor voice prevented twelve cupboards from hearing my case.',
        'REACTION_ANGRY',
      ],
      [
        'Indoor Voice',
        'I exist to keep allegations below conversational volume.',
        'REACTION_NEUTRAL',
      ],
      ['Justice Pigeon', 'The court sentences quiet to three nights outdoors.', 'FREEZE'],
    ],
    continuityFact: 'Quiet can receive a custodial outdoor sentence in Pet Law.',
    endingBeat: 'Every microphone rolls to the edge of the table.',
  }),
  draft({
    channelNumber: 404_404_404,
    channelName: 'Programme Not Found',
    programmeTitle: 'Replacement Audience Located',
    format: 'emergency',
    realityId: 'MISSING-SCHEDULE',
    visualStyle: 'vacant_continuity_suite',
    visualMedium: 'archive_film',
    castArchetype: 'mixed',
    premise: 'A missing programme locates an audience that does not remember requesting it.',
    tone: ['courteous', 'vacant', 'unsettling'],
    dialogue: [
      [
        'Continuity Vacancy',
        'The programme is absent, but its audience has been recovered.',
        'REACTION_NEUTRAL',
      ],
      ['Recovered Viewer Shape', 'I was watching a wall that knew my middle name.', 'PAUSE'],
      ['Continuity Vacancy', 'That wall has declined further episodes.', 'LOOK_AT'],
      ['Recovered Viewer Shape', 'Then why are the credits thanking me?', 'FREEZE'],
    ],
    continuityFact: 'Programme Not Found can recover audiences without recovering programmes.',
    endingBeat: 'Credits roll over an empty chair facing away.',
  }),
  draft({
    channelNumber: 2_000_000_017,
    channelName: 'Small Solar Television',
    programmeTitle: 'The Sun Needs a Quiet Corner',
    format: 'ident',
    realityId: 'NURSERY-STAR-8',
    visualStyle: 'felt_solar_nursery',
    visualMedium: 'paper_cutout',
    castArchetype: 'celestial',
    premise: 'A young sun practises shining without being perceived.',
    tone: ['gentle', 'overstimulated', 'warm'],
    dialogue: [
      ['Small Sun', 'Today I am using my inside brightness.', 'REACTION_NEUTRAL'],
      ['Cardboard Planet', 'We can still see you through four curtains.', 'LOOK_AT'],
      ['Small Sun', 'Seeing is a group activity. I have left the group.', 'PAUSE'],
      ['Cardboard Planet', 'Should we orbit more quietly?', 'FREEZE'],
    ],
    continuityFact: 'Small Sun has begun scheduled periods of unobserved shining.',
    endingBeat: 'The screen glows only around objects that look away.',
  }),
  draft({
    channelNumber: 65_536_001,
    channelName: 'Office of Unfinished Echoes',
    programmeTitle: 'Case Closed Halfway',
    format: 'public_access',
    realityId: 'ECHO-ADMIN-16',
    visualStyle: 'municipal_acoustic_counter',
    visualMedium: 'public_access_vhs',
    castArchetype: 'humanoid',
    premise: 'Residents collect the missing halves of things they stopped saying.',
    tone: ['procedural', 'hesitant', 'acoustic'],
    dialogue: [
      ['Echo Registrar', 'We recovered the end of your sentence from a stairwell in May.', 'IDLE'],
      ['Applicant Low', 'I do not remember beginning anything in May.', 'REACTION_CONFUSED'],
      ['Echo Registrar', 'The recovered phrase is: and that is why the roof knows.', 'POINT_AT'],
      ['Applicant Low', 'Please file it under things I refuse to start.', 'FREEZE'],
    ],
    continuityFact: 'Abandoned sentences may finish elsewhere and be reclaimed.',
    endingBeat: 'A filing cabinet repeats only the sound of closing.',
  }),
  draft({
    channelNumber: 900_000_006,
    channelName: 'Homes Seeking Owners',
    programmeTitle: 'A Family With Original Cornicing',
    format: 'shopping',
    realityId: 'PROPERTY-REVERSAL-2',
    visualStyle: 'reversed_property_tour',
    visualMedium: 'cel_shaded',
    castArchetype: 'mixed',
    premise: 'Three haunted houses compete to purchase a family with period features.',
    tone: ['aspirational', 'possessive', 'architectural'],
    dialogue: [
      [
        'House Agent',
        'Lot twelve is a family of four with excellent natural arguments.',
        'POINT_AT',
      ],
      ['Bungalow Spirit', 'Do the parents retain their original cornicing?', 'LOOK_AT'],
      ['House Agent', 'Yes, but the youngest bedroom is listed.', 'REACTION_NEUTRAL'],
      ['Bungalow Spirit', 'I can overlook that if they overlook my basement.', 'FREEZE'],
    ],
    continuityFact:
      'Haunted properties may bid competitively for architecturally notable families.',
    endingBeat: 'A tiny house raises its chimney to bid.',
  }),
  draft({
    channelNumber: 12_345_678,
    channelName: 'Instructions After Use',
    programmeTitle: 'Manual for a Cup You Already Broke',
    format: 'advert',
    realityId: 'POST-INSTRUCTION-5',
    visualStyle: 'instructional_colour_blocks',
    visualMedium: 'pixel_broadcast',
    castArchetype: 'talking_objects',
    premise:
      'An instruction service delivers perfect guidance immediately after it becomes useless.',
    tone: ['helpful', 'late', 'bright'],
    dialogue: [
      ['Manual Host', 'Step one: do not drop the cup in the manner just demonstrated.', 'POINT_AT'],
      ['Broken Cup', 'Could step two address my current plurality?', 'REACTION_CONFUSED'],
      ['Manual Host', 'Step two was available while you were singular.', 'REACTION_NEUTRAL'],
      ['Broken Cup', 'Then send the next manual to my replacement.', 'FREEZE'],
    ],
    continuityFact: 'Instructions After Use guarantees accuracy by arriving too late.',
    endingBeat: 'A sealed manual falls onto the remaining handle.',
  }),
  draft({
    channelNumber: 73_000_221,
    channelName: 'Lift Music Investigations',
    programmeTitle: 'The Melody Between Floors',
    format: 'news',
    realityId: 'ELEVATOR-AUDIO-7',
    visualStyle: 'investigative_lobby_feed',
    visualMedium: 'archive_film',
    castArchetype: 'humanoid',
    premise: 'Investigators trace lift music that continues playing after the building ends.',
    tone: ['investigative', 'restrained', 'vertical'],
    dialogue: [
      [
        'Reporter Vale',
        'The melody was last heard travelling above floor thirty-two.',
        'REACTION_NEUTRAL',
      ],
      ['Caretaker Moss', 'There is no thirty-three, only a button that hums.', 'POINT_AT'],
      ['Reporter Vale', 'Who selected the song?', 'LOOK_AT'],
      ['Caretaker Moss', 'The lift says the song selected us by weight.', 'FREEZE'],
    ],
    continuityFact: 'A lift melody is travelling beyond the registered top floor.',
    endingBeat: 'The floor indicator displays a musical note.',
  }),
  draft({
    channelNumber: 8_808_808,
    channelName: 'Memory Pawn',
    programmeTitle: 'A Childhood Smell With No Childhood',
    format: 'shopping',
    realityId: 'RECOLLECTION-MARKET',
    visualStyle: 'velvet_memory_auction',
    visualMedium: 'neon_wireframe',
    castArchetype: 'geometric_aliens',
    premise: 'A pawn channel auctions nostalgic memories that have never belonged to anyone.',
    tone: ['luxurious', 'wistful', 'commercial'],
    dialogue: [
      [
        'Auctioneer Venn',
        'Lot six is the smell of rain on a school you never attended.',
        'POINT_AT',
      ],
      ['Caller Amber', 'Does it include missing someone at the gate?', 'LOOK_AT'],
      [
        'Auctioneer Venn',
        'For another twelve credits, the person can remain unnamed.',
        'REACTION_NEUTRAL',
      ],
      ['Caller Amber', 'Reserve it before I remember why I cannot afford it.', 'FREEZE'],
    ],
    continuityFact: 'Unowned nostalgia is traded by Memory Pawn in unnamed lots.',
    endingBeat: 'The price display changes to a date instead of a number.',
  }),
  draft({
    channelNumber: 6_600_600,
    channelName: 'Slow Emergency Service',
    programmeTitle: 'Please Panic by Thursday',
    format: 'emergency',
    realityId: 'DEFERRED-ALERT-3',
    visualStyle: 'calm_delayed_warning',
    visualMedium: 'stop_motion',
    castArchetype: 'paper_puppets',
    premise: 'An emergency bulletin schedules public panic several days in advance.',
    tone: ['calm', 'delayed', 'bureaucratic'],
    dialogue: [
      [
        'Preparedness Officer',
        'A serious event is expected yesterday and will reach you on Thursday.',
        'REACTION_NEUTRAL',
      ],
      [
        'Calendar Deputy',
        'Citizens assigned to Wednesday should remain mildly concerned.',
        'POINT_AT',
      ],
      [
        'Preparedness Officer',
        'Do not panic early; it invalidates your emergency window.',
        'LOOK_AT',
      ],
      ['Calendar Deputy', 'Late panic may be carried into next month.', 'FREEZE'],
    ],
    continuityFact: 'Emergency responses are allocated by weekday and may be carried forward.',
    endingBeat: 'The warning siren opens a diary and books an appointment.',
  }),
  draft({
    channelNumber: 17_000_000,
    channelName: 'The Additional Relative',
    programmeTitle: 'There Is Another Uncle in the Hall',
    format: 'sitcom',
    realityId: 'HOUSEHOLD-PLUS-19',
    visualStyle: 'overcrowded_family_comedy',
    visualMedium: 'cel_shaded',
    castArchetype: 'mixed',
    premise:
      'A family discovers one more fully established relative whenever the front door opens.',
    tone: ['domestic', 'awkward', 'cumulative'],
    dialogue: [
      [
        'Mina Household',
        'Who is the man polishing our wedding photograph from inside it?',
        'REACTION_CONFUSED',
      ],
      ['Uncle Further', 'Mina, I taught you to forget my birthday.', 'REACTION_NEUTRAL'],
      ['Mina Household', 'We have no room for another shared history.', 'REACTION_ANGRY'],
      ['Uncle Further', 'That is why I brought the cousin who remembers the extension.', 'FREEZE'],
    ],
    continuityFact: 'Uncle Further joined the household with a disputed shared history.',
    endingBeat: 'The doorbell rings and the sofa makes space by itself.',
  }),
  draft({
    channelNumber: 4_444_004,
    channelName: 'Below Sea-Level Local',
    programmeTitle: 'Basement Tide at Six',
    format: 'news',
    realityId: 'SUBMERGED-MUNICIPALITY',
    visualStyle: 'underwater_regional_news',
    visualMedium: 'signal_corruption',
    castArchetype: 'geometric_aliens',
    premise: 'Local news reports a tide that occurs exclusively in one resident’s basement.',
    tone: ['regional', 'wet', 'earnest'],
    dialogue: [
      ['Anchor Reed', 'The six o’clock basement tide is two minutes early.', 'REACTION_NEUTRAL'],
      ['Cellar Reporter', 'A shoebox has issued a small-craft warning.', 'POINT_AT'],
      ['Anchor Reed', 'Has the boiler accepted evacuation?', 'LOOK_AT'],
      ['Cellar Reporter', 'No. It claims the water is visiting socially.', 'FREEZE'],
    ],
    continuityFact: 'One basement has a recognised tide and maritime warnings.',
    endingBeat: 'A lighthouse switches on beneath the news desk.',
  }),
  draft({
    channelNumber: 234_567_891,
    channelName: 'Question Pending',
    programmeTitle: 'Guess What You Were Asked',
    format: 'public_access',
    realityId: 'QUIZ-BACKWARDS-9',
    visualStyle: 'primary_colour_game_show',
    visualMedium: 'pixel_broadcast',
    castArchetype: 'humanoid',
    premise: 'Contestants receive an answer and must discover which question ruined their lives.',
    tone: ['cheerful', 'competitive', 'existential'],
    dialogue: [
      ['Host Correct', 'Your answer is: because the garden was listening.', 'POINT_AT'],
      [
        'Contestant Rue',
        'Was I asked why I stopped whispering near tomatoes?',
        'REACTION_CONFUSED',
      ],
      ['Host Correct', 'Close enough to lose the house but win the shed.', 'REACTION_NEUTRAL'],
      ['Contestant Rue', 'May I hear the question after the consequences?', 'FREEZE'],
    ],
    continuityFact: 'Question Pending awards property according to approximate unseen questions.',
    endingBeat: 'The scoreboard asks the contestant for identification.',
  }),
  draft({
    channelNumber: 5_050_505_050,
    channelName: 'Obituary Forecast',
    programmeTitle: 'A Strong Chance of Being Remembered Incorrectly',
    format: 'news',
    realityId: 'MEMORIAL-WEATHER-1',
    visualStyle: 'black_ribbon_weather_map',
    visualMedium: 'archive_film',
    castArchetype: 'paper_puppets',
    premise: 'A forecast predicts how inaccurately people will be remembered this afternoon.',
    tone: ['somber', 'meteorological', 'petty'],
    dialogue: [
      [
        'Memorial Forecaster',
        'By lunch, the east will remember you as taller but difficult near doors.',
        'POINT_AT',
      ],
      [
        'Legacy Correspondent',
        'The coast is already claiming I invented a disappointing soup.',
        'REACTION_CONFUSED',
      ],
      [
        'Memorial Forecaster',
        'That rumour should clear once the cousins arrive.',
        'REACTION_NEUTRAL',
      ],
      ['Legacy Correspondent', 'They are the low-pressure system that started it.', 'FREEZE'],
    ],
    continuityFact: 'Reputations form measurable regional weather after departure.',
    endingBeat: 'A weather symbol quietly changes its own surname.',
  }),
  draft({
    channelNumber: 37_000_037,
    channelName: 'Receipt Support',
    programmeTitle: 'Proof of Purchase Disputes Existing',
    format: 'public_access',
    realityId: 'TRANSACTION-AFTERCARE',
    visualStyle: 'thermal_paper_phone_in',
    visualMedium: 'paper_cutout',
    castArchetype: 'talking_objects',
    premise: 'A receipt calls customer support to dispute the purchase that created it.',
    tone: ['consumer', 'philosophical', 'crinkled'],
    dialogue: [
      ['Support Agent', 'For verification, please state the total printed at your feet.', 'IDLE'],
      ['Receipt 37', 'I refuse to reduce my origin to nineteen ninety-five.', 'REACTION_ANGRY'],
      ['Support Agent', 'Without a total, we cannot prove you happened.', 'REACTION_NEUTRAL'],
      ['Receipt 37', 'Then refund the event and keep the kettle.', 'FREEZE'],
    ],
    continuityFact: 'Receipts may contest the transactions responsible for their existence.',
    endingBeat: 'The receipt feeds itself backward into a silent till.',
  }),
  draft({
    channelNumber: 91_828_182,
    channelName: 'Door Museum Live',
    programmeTitle: 'The Entrance That Refuses Exhibits',
    format: 'news',
    realityId: 'THRESHOLD-CULTURE',
    visualStyle: 'museum_after_hours_feed',
    visualMedium: 'stop_motion',
    castArchetype: 'mixed',
    premise: 'A museum entrance refuses to admit the doors selected for its exhibition.',
    tone: ['cultural', 'territorial', 'polite'],
    dialogue: [
      [
        'Curator Hinge',
        'Our entrance says displaying other doors creates a conflict of access.',
        'REACTION_NEUTRAL',
      ],
      ['Gallery Door', 'We travelled six walls to be excluded here.', 'REACTION_ANGRY'],
      ['Curator Hinge', 'The exhibition will proceed through a window.', 'POINT_AT'],
      ['Gallery Door', 'That is not an entrance. That is gossip in architecture.', 'FREEZE'],
    ],
    continuityFact: 'The Door Museum entrance can deny access to rival doors.',
    endingBeat: 'The gallery exits through a picture frame.',
  }),
  draft({
    channelNumber: 1_000_000_003,
    channelName: 'Small Claims Against Gravity',
    programmeTitle: 'The Falling Cup Seeks Damages',
    format: 'public_access',
    realityId: 'PHYSICS-CIVIL-COURT',
    visualStyle: 'county_court_zero_g',
    visualMedium: 'cel_shaded',
    castArchetype: 'talking_objects',
    premise:
      'Household objects bring civil claims against gravity for repeated downward treatment.',
    tone: ['legal', 'weary', 'physical'],
    dialogue: [
      ['Judge Level', 'The claimant alleges a pattern of being pulled without consent.', 'IDLE'],
      ['Cup Claimant', 'Gravity waited until I was full and emotionally glazed.', 'REACTION_ANGRY'],
      ['Counsel Down', 'My client applies equally to all objects.', 'REACTION_NEUTRAL'],
      ['Judge Level', 'Equality is not a defence when the floor keeps receipts.', 'FREEZE'],
    ],
    continuityFact: 'Gravity faces a civil claim supported by floor testimony.',
    endingBeat: 'The judge’s gavel refuses to come back down.',
  }),
  draft({
    channelNumber: 314_159_265,
    channelName: 'Kitchen Performance Review',
    programmeTitle: 'The Ingredients Score the Chef',
    format: 'shopping',
    realityId: 'CULINARY-MANAGEMENT-6',
    visualStyle: 'corporate_cookery_review',
    visualMedium: 'public_access_vhs',
    castArchetype: 'talking_objects',
    premise: 'Ingredients conduct a formal performance review of the chef cooking them.',
    tone: ['culinary', 'managerial', 'tense'],
    dialogue: [
      ['Chef Lark', 'I have prepared the onions with confidence and medium heat.', 'POINT_AT'],
      [
        'Senior Onion',
        'Your confidence was not in the agreed recipe objectives.',
        'REACTION_NEUTRAL',
      ],
      ['Pepper Grinder', 'We noted limited seasoning leadership in quarter two.', 'LOOK_AT'],
      ['Chef Lark', 'Can we discuss this after I stop being on probation?', 'FREEZE'],
    ],
    continuityFact: 'Ingredients issue quarterly performance reviews to active chefs.',
    endingBeat: 'The chopping board schedules a private exit interview.',
  }),
  draft({
    channelNumber: 8_675_309_112,
    channelName: 'Commuter Thought Rail',
    programmeTitle: 'The 08:12 to Something You Abandoned',
    format: 'news',
    realityId: 'MENTAL-TRANSIT-22',
    visualStyle: 'station_departure_board_mind',
    visualMedium: 'neon_wireframe',
    castArchetype: 'geometric_aliens',
    premise: 'A commuter service transports abandoned thoughts back to their original people.',
    tone: ['informational', 'crowded', 'introspective'],
    dialogue: [
      [
        'Platform Announcer',
        'The service carrying forgotten ambitions is delayed by self-doubt.',
        'REACTION_NEUTRAL',
      ],
      ['Thought Inspector', 'Unclaimed ideas must not block the doors with potential.', 'POINT_AT'],
      ['Platform Announcer', 'A memory of learning the violin has boarded first class.', 'LOOK_AT'],
      ['Thought Inspector', 'Its owner is hiding behind the ticket barrier.', 'FREEZE'],
    ],
    continuityFact: 'Abandoned ambitions commute independently and can upgrade themselves.',
    endingBeat: 'The departure board displays a passenger’s unfinished sentence.',
  }),
  draft({
    channelNumber: 999_000_999,
    channelName: 'Calendar Recall Authority',
    programmeTitle: 'Thursday Must Be Returned',
    format: 'emergency',
    realityId: 'WEEK-RECALL-44',
    visualStyle: 'consumer_day_recall',
    visualMedium: 'signal_corruption',
    castArchetype: 'humanoid',
    premise:
      'An urgent recall orders citizens to return a defective Thursday in its original condition.',
    tone: ['urgent', 'consumer', 'temporal'],
    dialogue: [
      [
        'Recall Officer',
        'Thursday batch eleven contains an unauthorised second afternoon.',
        'REACTION_NEUTRAL',
      ],
      ['Week Technician', 'Do not attempt to finish work inside the affected hours.', 'POINT_AT'],
      ['Recall Officer', 'Return the day with all conversations still attached.', 'LOOK_AT'],
      ['Week Technician', 'Friday will be issued only after inspection.', 'FREEZE'],
    ],
    continuityFact: 'One batch of Thursday has been recalled for containing a second afternoon.',
    endingBeat: 'The on-screen date folds itself into a returns envelope.',
  }),
  draft({
    channelNumber: 7_100_000_001,
    channelName: 'Shadow Migration Watch',
    programmeTitle: 'The Long Journey Across the Carpet',
    format: 'news',
    realityId: 'LOW-LIGHT-NATURE',
    visualStyle: 'natural_history_lamppost',
    visualMedium: 'archive_film',
    castArchetype: 'paper_puppets',
    premise: 'A nature documentary follows household shadows migrating away from their objects.',
    tone: ['reverent', 'observational', 'dim'],
    dialogue: [
      [
        'Naturalist Umber',
        'At dusk, the lamp shadow leaves first, travelling under the sofa.',
        'PAUSE',
      ],
      ['Field Shade', 'The vase shadow is carrying enough darkness for winter.', 'POINT_AT'],
      [
        'Naturalist Umber',
        'Its vase will wake lighter and unable to explain why.',
        'REACTION_NEUTRAL',
      ],
      ['Field Shade', 'Silence now. The wall has noticed us noticing.', 'FREEZE'],
    ],
    continuityFact: 'Domestic shadows migrate seasonally without their source objects.',
    endingBeat: 'The presenter’s shadow continues walking after the presenter stops.',
  }),
  draft({
    channelNumber: 62_400_711,
    channelName: 'Private Thought Security',
    programmeTitle: 'An Alarm Only Your Doubts Can Hear',
    format: 'advert',
    realityId: 'MENTAL-HOME-SAFETY',
    visualStyle: 'late_night_security_offer',
    visualMedium: 'pixel_broadcast',
    castArchetype: 'mixed',
    premise: 'A security company sells silent alarms that frighten intrusive thoughts away.',
    tone: ['reassuring', 'commercial', 'paranoid'],
    dialogue: [
      [
        'Security Host',
        'When a doubt enters, the alarm emits a confidence only it can hear.',
        'POINT_AT',
      ],
      [
        'Satisfied Customer',
        'Mine chased a worry into the neighbour’s future.',
        'REACTION_NEUTRAL',
      ],
      ['Security Host', 'Optional zoning keeps practical concerns in the utility room.', 'LOOK_AT'],
      ['Satisfied Customer', 'I have not checked the utility room since installation.', 'FREEZE'],
    ],
    continuityFact: 'Private Thought Security can relocate worries into neighbouring futures.',
    endingBeat: 'A warning light flashes behind the customer’s forehead.',
  }),
  draft({
    channelNumber: 30_303_030,
    channelName: 'Municipal Silence Desk',
    programmeTitle: 'Your Noise Was Not Loud Enough to Exist',
    format: 'public_access',
    realityId: 'QUIET-BOROUGH-10',
    visualStyle: 'acoustic_permit_office',
    visualMedium: 'public_access_vhs',
    castArchetype: 'humanoid',
    premise: 'Residents apply for official recognition of noises nobody else heard.',
    tone: ['civic', 'quiet', 'earnest'],
    dialogue: [
      [
        'Silence Clerk',
        'Your midnight bang falls below the threshold for municipal existence.',
        'IDLE',
      ],
      ['Resident Hush', 'It woke the part of me that pays council tax.', 'REACTION_CONFUSED'],
      ['Silence Clerk', 'That department is not an approved witness.', 'POINT_AT'],
      ['Resident Hush', 'Can I resubmit the fear at a higher volume?', 'FREEZE'],
    ],
    continuityFact: 'Unheard noises require civic recognition before they officially occur.',
    endingBeat: 'A sound-level meter displays the word perhaps.',
  }),
  draft({
    channelNumber: 4_294_967_291,
    channelName: 'Final Address Service',
    programmeTitle: 'Your House Has Moved On',
    format: 'news',
    realityId: 'POSTAL-ENDPOINT-64',
    visualStyle: 'postal_change_bulletin',
    visualMedium: 'cel_shaded',
    castArchetype: 'mixed',
    premise: 'A postal service explains that a person’s address has relocated without them.',
    tone: ['official', 'sympathetic', 'displaced'],
    dialogue: [
      [
        'Address Officer',
        'Your home left forwarding details but asked us not to share them.',
        'REACTION_NEUTRAL',
      ],
      ['Former Resident', 'The furniture was still inside me when it went.', 'REACTION_CONFUSED'],
      ['Address Officer', 'You may continue receiving post as a historical location.', 'POINT_AT'],
      ['Former Resident', 'Please return anything addressed to who I was there.', 'FREEZE'],
    ],
    continuityFact:
      'Addresses can relocate independently and leave residents as historical locations.',
    endingBeat: 'The studio postcode changes while the walls remain still.',
  }),
  draft({
    channelNumber: 707_707_707,
    channelName: 'Triangle Clubhouse',
    programmeTitle: 'Three Sides Is Plenty Today',
    format: 'ident',
    realityId: 'GEOMETRY-NURSERY-3',
    visualStyle: 'crayon_shape_club',
    visualMedium: 'paper_cutout',
    castArchetype: 'geometric_aliens',
    premise: 'A tired triangle refuses pressure to become a more advanced shape.',
    tone: ['childlike', 'supportive', 'geometric'],
    dialogue: [
      [
        'Tilly Triangle',
        'Everyone keeps asking what I will be when I get another side.',
        'REACTION_CONFUSED',
      ],
      ['Circle Helper', 'You do not owe anybody a corner plan.', 'LOOK_AT'],
      ['Tilly Triangle', 'I have three excellent directions and no vacancies.', 'REACTION_NEUTRAL'],
      ['Circle Helper', 'Then we will roll around your boundaries.', 'FREEZE'],
    ],
    continuityFact: 'Tilly Triangle has rejected compulsory geometric advancement.',
    endingBeat: 'A square quietly removes one side in solidarity.',
  }),
  draft({
    channelNumber: 5_555_000_042,
    channelName: 'Cloud Conduct News',
    programmeTitle: 'One Cloud Remains Under Investigation',
    format: 'news',
    realityId: 'SKY-STANDARDS-5',
    visualStyle: 'aerial_ethics_bulletin',
    visualMedium: 'stop_motion',
    castArchetype: 'celestial',
    premise:
      'A cloud is investigated for following one resident through several unrelated weathers.',
    tone: ['serious', 'meteorological', 'personal'],
    dialogue: [
      [
        'Sky Anchor',
        'Cloud forty-two denies targeting Mr Bell with localised disappointment.',
        'REACTION_NEUTRAL',
      ],
      [
        'Cloud Counsel',
        'My client was simply raining in the same emotional direction.',
        'POINT_AT',
      ],
      ['Sky Anchor', 'It attended his wedding disguised as acceptable weather.', 'LOOK_AT'],
      ['Cloud Counsel', 'That disguise has since evaporated.', 'FREEZE'],
    ],
    continuityFact: 'Cloud forty-two faces an inquiry into persistent personal weather.',
    endingBeat: 'A small cloud appears directly above the anchor.',
  }),
  draft({
    channelNumber: 100_000_000,
    channelName: 'Anecdote Insurance',
    programmeTitle: 'Cover Against Becoming a Story',
    format: 'advert',
    realityId: 'SOCIAL-RISK-100',
    visualStyle: 'restrained_financial_commercial',
    visualMedium: 'neon_wireframe',
    castArchetype: 'humanoid',
    premise: 'An insurer protects customers from becoming amusing stories told by acquaintances.',
    tone: ['professional', 'socially anxious', 'protective'],
    dialogue: [
      [
        'Insurance Adviser',
        'One unusual sandwich can follow your name through an entire office.',
        'REACTION_NEUTRAL',
      ],
      [
        'Policy Holder',
        'My colleagues now introduce me as the gazebo incident.',
        'REACTION_CONFUSED',
      ],
      [
        'Insurance Adviser',
        'Premium cover replaces all punchlines with a neutral administrative delay.',
        'POINT_AT',
      ],
      ['Policy Holder', 'Can it also insure the pause before they remember me?', 'FREEZE'],
    ],
    continuityFact:
      'Anecdote Insurance can replace personal punchlines with administrative delays.',
    endingBeat: 'The customer’s name is pixelated before anyone speaks it.',
  }),
  draft({
    channelNumber: 9_001_001_009,
    channelName: 'Future Rubbish Archaeology',
    programmeTitle: 'Excavating Next Week’s Bin',
    format: 'news',
    realityId: 'LANDFILL-AHEAD-90',
    visualStyle: 'speculative_dig_documentary',
    visualMedium: 'archive_film',
    castArchetype: 'mixed',
    premise: 'Archaeologists excavate household rubbish from a week that has not occurred.',
    tone: ['scholarly', 'premature', 'domestic'],
    dialogue: [
      [
        'Future Archaeologist',
        'This yoghurt lid suggests Tuesday ends with unexpected guests.',
        'POINT_AT',
      ],
      ['Site Analyst', 'The untouched salad indicates negotiations failed.', 'REACTION_NEUTRAL'],
      [
        'Future Archaeologist',
        'We also found a receipt for an apology purchased on Friday.',
        'LOOK_AT',
      ],
      ['Site Analyst', 'Seal the trench. Somebody is taking the bin out early.', 'FREEZE'],
    ],
    continuityFact: 'Archaeologists can excavate domestic waste several days before disposal.',
    endingBeat: 'A rubbish bag rises pristine from beneath the studio floor.',
  }),
  draft({
    channelNumber: 6_250_000_601,
    channelName: 'The Reverse Aquarium',
    programmeTitle: 'Fish Observe a Nervous Office',
    format: 'public_access',
    realityId: 'GLASS-OUTSIDE-13',
    visualStyle: 'aquatic_workplace_observation',
    visualMedium: 'signal_corruption',
    castArchetype: 'geometric_aliens',
    premise: 'Fish inside a television calmly document office workers swimming through paperwork.',
    tone: ['aquatic', 'observational', 'corporate'],
    dialogue: [
      [
        'Fish Naturalist',
        'The junior manager circles the copier before attempting a print.',
        'PAUSE',
      ],
      [
        'Glass Assistant',
        'Notice how the shoal avoids the meeting room during feeding time.',
        'POINT_AT',
      ],
      [
        'Fish Naturalist',
        'One worker has built a nest from confidential drafts.',
        'REACTION_NEUTRAL',
      ],
      ['Glass Assistant', 'The tank lights are dimming. They think we have gone home.', 'FREEZE'],
    ],
    continuityFact: 'Aquarium fish study office workers as a captive aquatic species.',
    endingBeat: 'A human hand taps the glass from inside the scene.',
  }),
  draft({
    channelNumber: 222_000_222,
    channelName: 'Lost Property Prophecy',
    programmeTitle: 'Tomorrow’s Umbrella Has Been Handed In',
    format: 'shopping',
    realityId: 'CLAIMS-AHEAD-2',
    visualStyle: 'station_lost_property_counter',
    visualMedium: 'public_access_vhs',
    castArchetype: 'talking_objects',
    premise: 'A lost-property office returns objects before their owners have lost them.',
    tone: ['helpful', 'premature', 'rainy'],
    dialogue: [
      [
        'Claims Attendant',
        'This umbrella will be yours after the argument beside platform five.',
        'POINT_AT',
      ],
      ['Future Owner', 'Can I avoid the argument by refusing the umbrella?', 'REACTION_CONFUSED'],
      [
        'Claims Attendant',
        'Then it will belong to the person you become in the rain.',
        'REACTION_NEUTRAL',
      ],
      ['Future Owner', 'Does that person have proof of loss?', 'FREEZE'],
    ],
    continuityFact: 'Lost Property Prophecy receives objects before the events that lose them.',
    endingBeat: 'The umbrella opens and begins raining upward.',
  }),
  draft({
    channelNumber: 8_000_000_008,
    channelName: 'Sleep Maintenance Window',
    programmeTitle: 'Dreams Offline for Essential Repairs',
    format: 'emergency',
    realityId: 'NIGHT-INFRASTRUCTURE',
    visualStyle: 'overnight_service_notice',
    visualMedium: 'pixel_broadcast',
    castArchetype: 'paper_puppets',
    premise: 'A maintenance notice suspends dreaming while engineers replace a recurring corridor.',
    tone: ['technical', 'nighttime', 'reassuring'],
    dialogue: [
      [
        'Night Engineer',
        'Dream service will pause while corridor seven is made less endless.',
        'REACTION_NEUTRAL',
      ],
      [
        'Sleep Coordinator',
        'Users may experience a temporary morning with no symbolic meaning.',
        'POINT_AT',
      ],
      ['Night Engineer', 'Do not enter memories marked wet paint.', 'LOOK_AT'],
      ['Sleep Coordinator', 'Normal confusion should resume before waking.', 'FREEZE'],
    ],
    continuityFact: 'Recurring dream corridors undergo scheduled infrastructure maintenance.',
    endingBeat: 'A progress bar falls asleep at ninety-nine percent.',
  }),
  draft({
    channelNumber: 1_010_101_011,
    channelName: 'Museum of Current Events',
    programmeTitle: 'Breaking News Enters the Collection',
    format: 'news',
    realityId: 'PRESENT-ARCHIVE',
    visualStyle: 'museum_newsroom_hybrid',
    visualMedium: 'cel_shaded',
    castArchetype: 'paper_puppets',
    premise:
      'A museum acquires events while they are still happening and asks participants to keep still.',
    tone: ['curatorial', 'urgent', 'frozen'],
    dialogue: [
      [
        'Curator Live',
        'This developing argument has been accessioned under domestic history.',
        'REACTION_NEUTRAL',
      ],
      [
        'Argument Participant',
        'May I finish disagreeing before you place the rope around us?',
        'REACTION_ANGRY',
      ],
      ['Curator Live', 'Movement lowers the event’s condition rating.', 'POINT_AT'],
      ['Argument Participant', 'Then exhibit the version where I was right.', 'FREEZE'],
    ],
    continuityFact: 'The Museum of Current Events collects incidents before they conclude.',
    endingBeat: 'A red breaking-news banner is mounted in a glass case.',
  }),
  draft({
    channelNumber: 50_000_000_005,
    channelName: 'Five-Minute Planet',
    programmeTitle: 'Civilisation Before the Next Ident',
    format: 'ident',
    realityId: 'FAST-WORLD-5',
    visualStyle: 'compressed_planetary_history',
    visualMedium: 'stop_motion',
    castArchetype: 'celestial',
    premise: 'A tiny planet builds and abandons a civilisation during one station ident.',
    tone: ['grand', 'hurried', 'tiny'],
    dialogue: [
      [
        'Planet Narrator',
        'The eastern continent has invented doors and immediately regrets corridors.',
        'REACTION_NEUTRAL',
      ],
      [
        'Tiny Historian',
        'Our bronze age was cancelled due to a shortage of previous ages.',
        'POINT_AT',
      ],
      ['Planet Narrator', 'Please prepare for the customary fall of the soft empire.', 'LOOK_AT'],
      ['Tiny Historian', 'Can we renew for another geological minute?', 'FREEZE'],
    ],
    continuityFact: 'Five-Minute Planet completes civilisations within a single ident.',
    endingBeat: 'The planet displays end credits across a newly formed ocean.',
  }),
];
